version: 0.2

env:
  variables:
    DOCKER_BUILDKIT: "1"

phases:
  pre_build:
    commands:
      - echo "=== Pre-build phase ==="
      - export AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - export ECR_REGISTRY="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com"
      - echo "ECR Registry $ECR_REGISTRY"
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY
      - echo "Pulling base images from public ECR..."
      - docker pull public.ecr.aws/docker/library/python:3.12-slim || true
      - docker pull public.ecr.aws/docker/library/node:20-slim || true
      - docker pull quay.io/keycloak/keycloak:23.0 || true
      - docker pull grafana/grafana:12.3.1 || true
      - echo "Pulling existing images for cache..."
      - docker pull $ECR_REGISTRY/mcp-gateway-registry:latest || true
      - docker pull $ECR_REGISTRY/mcp-gateway-auth-server:latest || true
      - docker pull $ECR_REGISTRY/keycloak:latest || true
      - docker pull $ECR_REGISTRY/mcp-gateway-grafana:latest || true
      - mkdir -p agents/a2a/src/flight-booking-agent/.tmp agents/a2a/src/travel-assistant-agent/.tmp
      - cp agents/a2a/pyproject.toml agents/a2a/uv.lock agents/a2a/src/flight-booking-agent/.tmp/ 2>/dev/null || true
      - cp agents/a2a/pyproject.toml agents/a2a/uv.lock agents/a2a/src/travel-assistant-agent/.tmp/ 2>/dev/null || true

  build:
    commands:
      - echo "=== Build phase ==="
      - docker build --cache-from $ECR_REGISTRY/mcp-gateway-registry:latest -t $ECR_REGISTRY/mcp-gateway-registry:latest -f docker/Dockerfile.registry .
      - docker push $ECR_REGISTRY/mcp-gateway-registry:latest
      - docker build --cache-from $ECR_REGISTRY/mcp-gateway-auth-server:latest -t $ECR_REGISTRY/mcp-gateway-auth-server:latest -f docker/Dockerfile.auth .
      - docker push $ECR_REGISTRY/mcp-gateway-auth-server:latest
      - docker build --cache-from $ECR_REGISTRY/keycloak:latest -t $ECR_REGISTRY/keycloak:latest -f docker/keycloak/Dockerfile docker/keycloak
      - docker push $ECR_REGISTRY/keycloak:latest
      - docker build -t $ECR_REGISTRY/mcp-gateway-currenttime:latest -f docker/Dockerfile.mcp-server servers/currenttime
      - docker push $ECR_REGISTRY/mcp-gateway-currenttime:latest
      - docker build -t $ECR_REGISTRY/mcp-gateway-mcpgw:latest -f docker/Dockerfile.mcp-server servers/mcpgw
      - docker push $ECR_REGISTRY/mcp-gateway-mcpgw:latest
      - docker build -t $ECR_REGISTRY/mcp-gateway-realserverfaketools:latest -f docker/Dockerfile.mcp-server servers/realserverfaketools
      - docker push $ECR_REGISTRY/mcp-gateway-realserverfaketools:latest
      - docker build -t $ECR_REGISTRY/mcp-gateway-flight-booking-agent:latest -f agents/a2a/src/flight-booking-agent/Dockerfile agents/a2a/src/flight-booking-agent
      - docker push $ECR_REGISTRY/mcp-gateway-flight-booking-agent:latest
      - docker build -t $ECR_REGISTRY/mcp-gateway-travel-assistant-agent:latest -f agents/a2a/src/travel-assistant-agent/Dockerfile agents/a2a/src/travel-assistant-agent
      - docker push $ECR_REGISTRY/mcp-gateway-travel-assistant-agent:latest
      - echo "Building Grafana OSS container..."
      - docker build -t $ECR_REGISTRY/mcp-gateway-grafana:latest -f cloudformation/aws-ecs/grafana/Dockerfile cloudformation/aws-ecs/grafana
      - docker push $ECR_REGISTRY/mcp-gateway-grafana:latest

  post_build:
    commands:
      - echo "Build completed on $(date)"
      - echo "All images pushed to ECR"

cache:
  paths:
    - '/root/.cache/pip/**/*'
    - '/root/.npm/**/*'
